plancraft:
  model: meta-llama/Meta-Llama-3.1-8B-Instruct
  tokenizer: meta-llama/Meta-Llama-3.1-8B-Instruct
  adapter: gautierdag/oa-llama3-r64-a32
  num_generations: 5
  mode: "act"
  hot_cache: True
  max_steps: 80
  quantize: False
  environment:
    symbolic: True
    symbolic_observation_space: True
    symbolic_action_space: True
  split: val
  batch_size: 1
  max_message_window: 40
  resume: False
  output_dir: "outputs"
  few_shot: True
  system_prompt: True
wandb:
  project: "plancraft"
  entity: "itl"
  mode: "online"
launch:
  command: "python main.py"
  job_name: "plancraft-s2234411"
  gpu_limit: 1
  gpu_product: NVIDIA-A100-SXM4-80GB
  cpu_request: 12
  ram_request: 80Gi
  interactive: False
  namespace: informatics
  env_vars:
    HF_TOKEN:
      secret_name: s2234411-hf
      key: HF_TOKEN
    OPENAI_API_KEY:
      secret_name: s2234411-openai
      key: OPENAI_API_KEY
    WANDB_API_KEY:
      secret_name: s2234411-wandb
      key: WANDB_API_KEY
    SLACK_WEBHOOK:
      secret_name: s2234411-slack-webhook
      key: SLACK_WEBHOOK