plancraft:
  model: dummy
  tokenizer: dummy
  num_generations: 1
  mode: dummy
  hot_cache: True
  max_steps: 80
  quantize: False
  environment:
    symbolic: True
    symbolic_observation_space: True
    symbolic_action_space: True
  split: val
  batch_size: 1
  max_message_window: 100
  resume: False
  output_dir: "outputs"
  few_shot: False
  system_prompt: False