plancraft:
  model: hosted_vllm/google/gemma-3-27b-it
  tokenizer: hosted_vllm/google/gemma-3-27b-it
  num_generations: 5
  mode: "act"
  max_steps: 30
  split: test
  max_message_window: 40
  resume: False
  output_dir: "outputs"
wandb:
  project: "plancraft-new"
  entity: "itl"
  mode: "online"