plancraft:
  model: gpt-4o-mini
  tokenizer: gpt-4o-mini"
  num_generations: 5
  mode: "act"
  max_steps: 30
  split: test.small
  max_message_window: 40
  resume: False
  output_dir: "outputs"
wandb:
  project: "plancraft"
  entity: "itl"
  mode: "online"