plancraft:
  model: meta-llama/Meta-Llama-3.1-70B-Instruct
  tokenizer: meta-llama/Meta-Llama-3.1-70B-Instruct
  num_generations: 5
  mode: "act"
  max_steps: 30
  split: test.small
  max_message_window: 40
  resume: False
  output_dir: "outputs"
wandb:
  project: "plancraft"
  entity: "itl"
  mode: "online"