plancraft:
  model: hosted_vllm/Qwen/Qwen3-30B-A3B
  tokenizer: hosted_vllm/Qwen/Qwen3-30B-A3B
  num_generations: 3
  mode: "act"
  max_steps: 30
  split: test
  max_message_window: 40
  resume: False
  output_dir: "outputs"
wandb:
  project: "plancraft-new"
  entity: "itl"
  mode: "online"