goal_model:
  use_horizon: 1

eval:
  seed: 0
  num_evals: 5
  # num_evals: 1
  env_name: "Plains"
  # tasks: ['obtain_fence','obtain_fence_gate','obtain_boat','obtain_trapdoor','obtain_bowl']
  tasks: ["obtain_planks"]
  model: oracle

data:
  filters:
    - log
    - sheep
    - cow
    - pig
    - stone

model:
  load_ckpt_path: /home/gautier/Desktop/models/controller.pt

pretrains:
  clip_path: /home/gautier/Desktop/models/MINECLIP.pth

record:
  frames: True

simulator:
  resolution: [640, 480]
