goal_model:
  use_horizon: 1

eval:
  num_evals: 5
  env_name: "Plains"
  task_name: "obtain_planks"

data:
  filters:
    - log
    - sheep
    - cow
    - pig
    - stone

model:
  load_ckpt_path: "/Users/gautier/Github/minecraft/models/controller.pt"

pretrains:
  clip_path: /Users/gautier/Github/minecraft/models/MINECLIP.pth

record:
  frames: True

simulator:
  resolution: [640, 480]
