plancraft:
  # model: microsoft/Phi-3-mini-128k-instruct
  # model: meta-llama/Meta-Llama-3-8B-Instruct
  # model: CohereForAI/c4ai-command-r-v01
  model: "gpt-4o"
  num_generations: 1
  # mode: "react"
  mode: "oracle"
  # mode: "dummy"
  max_steps: 80
  quantize: False #int8
  environment:
    symbolic: True
    symbolic_observation_space: True
    symbolic_action_space: True
  split: val
  batch_size: 1
  max_message_window: 30
  resume: True
  output_dir: "outputs"
wandb:
  project: "plancraft"
  entity: "itl"
  mode: "offline"
launch:
  command: "python main.py"
  job_name: "plancraft-s2234411"
  gpu_limit: 1
  gpu_product: NVIDIA-A100-SXM4-80GB
  cpu_request: 12
  ram_request: 80Gi
  interactive: False
  namespace: informatics
  env_vars:
    HF_TOKEN:
      secret_name: s2234411-hf
      key: HF_TOKEN
    OPENAI_API_KEY:
      secret_name: s2234411-openai
      key: OPENAI_API_KEY
    WANDB_API_KEY:
      secret_name: s2234411-wandb
      key: WANDB_API_KEY
    SLACK_WEBHOOK:
      secret_name: s2234411-slack-webhook
      key: SLACK_WEBHOOK