goal_model:
  use_horizon: 1

eval:
  seed: 0
  num_evals: 30
  env_name: "Plains"
  tasks: ["obtain_planks"]

data:
  filters:
    - log
    - sheep
    - cow
    - pig
    - stone

model:
  load_ckpt_path: /home/gautier/Desktop/models/controller.pt

pretrains:
  clip_path: /home/gautier/Desktop/models/MINECLIP.pth

record:
  frames: True

simulator:
  resolution: [640, 480]
