plancraft:
  # model: meta-llama/Meta-Llama-3-70B-Instruct
  # model: CohereForAI/c4ai-command-r-v01
  # model: "gpt-4o"
  # model: mistralai/Mistral-7B-Instruct-v0.3
  # model: oracle
  # model: HuggingFaceM4/idefics2-8b-chatty
  # model: /plancraft/outputs/llama3-r64-a32/final
  # model: google/gemma-2-9b-it
  # tokenizer: google/gemma-2-9b-it
  model: /plancraft/outputs/oa-idefics2-r16-a32/oa-idefics2-r16-a32
  # tokenizer: /nfs/public/hf/models/meta-llama/Meta-Llama-3-8B-Instruct
  # model: /plancraft/outputs/hf-idefics2-r16-a32/final
  tokenizer: /nfs/public/hf/models/HuggingFaceM4/idefics2-8b-chatty
  num_generations: 1
  mode: "act"
  # mode: "oracle"
  # mode: "dummy"
  hot_cache: True
  max_steps: 80
  quantize: False
  environment:
    symbolic: False
    symbolic_observation_space: True
    symbolic_action_space: True
  split: val
  batch_size: 1
  max_message_window: 40
  resume: False
  output_dir: "outputs"
wandb:
  project: "plancraft"
  entity: "itl"
  mode: "online"
launch:
  command: "python main.py"
  job_name: "plancraft-s2234411"
  gpu_limit: 1
  gpu_product: NVIDIA-A100-SXM4-80GB
  cpu_request: 12
  ram_request: 80Gi
  interactive: False
  namespace: informatics
  env_vars:
    HF_TOKEN:
      secret_name: s2234411-hf
      key: HF_TOKEN
    OPENAI_API_KEY:
      secret_name: s2234411-openai
      key: OPENAI_API_KEY
    WANDB_API_KEY:
      secret_name: s2234411-wandb
      key: WANDB_API_KEY
    SLACK_WEBHOOK:
      secret_name: s2234411-slack-webhook
      key: SLACK_WEBHOOK