training: 
  base_model: "llama3"
  trace_mode: "ota"
  push_to_hub: True
  lora_r: 64
  lora_alpha: 32
  lora_dropout: 0.1
  seed: 42
  batch_size: 1
  max_seq_length: 8000
  gradient_accumulation_steps: 4
  max_window_length: 40
  learning_rate: 2e-4
  max_grad_norm: 0.3
  warmup_ratio: 0.05
  num_train_epochs: 5
  num_workers: 16
  only_assistant: True
wandb:
  project: "plancraft-train"
  entity: "itl"
  mode: "online"
launch:
  command: "python main.py"
  job_name: "plancraft-s2234411"
  gpu_limit: 1
  gpu_product: NVIDIA-A100-SXM4-80GB
  cpu_request: 12
  ram_request: 80Gi
  interactive: False
  namespace: informatics
  env_vars:
    HF_TOKEN:
      secret_name: s2234411-hf
      key: HF_TOKEN
    OPENAI_API_KEY:
      secret_name: s2234411-openai
      key: OPENAI_API_KEY
    WANDB_API_KEY:
      secret_name: s2234411-wandb
      key: WANDB_API_KEY
    SLACK_WEBHOOK:
      secret_name: s2234411-slack-webhook
      key: SLACK_WEBHOOK